#!/bin/bash
VERSION=0.00.1
source ~/.bashrc


function install_git(){
echo_info "Installing git cli"
echo_info "++++++++++"
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
echo_info "adding dependencies"
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
echo_info "performaing update"
sudo apt update
echo_info "Installing gh"
sudo apt install gh
echo_ok "Installation done"
}


function test1(){
echo_ok 'everything is ok'
}




PS3='Please enter your choice: '
options=("Install git" "test1" "Option 3" "QUIT")
select opt in "${options[@]}"
do
	case $opt in
		"Install git")
			install_git
			;;
		"test1")
            		test1
			echo "you chose choice 2"
            		;;
        	"Option 3")
            		echo "you chose choice $REPLY which is $opt"
            		;;
        	"Quit")
            		break
            		;;
        	*) echo "invalid option $REPLY";;
    	esac
done

	
