#!/bin/bash
VERSION=0.00.1
source ~/.bashrc



PS3='Please enter your choice: '
options=("Option 1" "Option 2" "Option 3" "QUIT")
select opt in "${options[@]}"
do
	case $opt in
		"Option 1")
			echo_info "Install git"
			;;
		 "Option 2")
            		echo "you chose choice 2"
            		;;
        	"Option 3")
            		echo "you chose choice $REPLY which is $opt"
            		;;
        	"Quit")
            		break
            		;;
        	*) echo "invalid option $REPLY";;
    	esac
done







	
