#!/bin/bash
#SETUP-FUNCTIONS

function install_git(){
  echo_info "Installing git cli"
  echo_info "++++++++++"
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
echo_info "adding dependencies"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  echo_info "performaing update"
  sudo apt update
  echo_info "Installing gh"
  sudo apt install gh
  echo_ok "Installation done"
}

function ping_website(){
  echo_info "Please enter website to ping (www.example.com)"
  read website
  echo_info "How often do you want to ping $website ?"
  read amount
  echo_info "Pinging $website - $amount times!"
  ping -c $amount $website
  echo_ok "Ping done!"
  exit 0
}

function install_zsh(){
  echo_info "Starting full system update"
  echo_info "++++++++++"
  sudo apt update ; sudo apt full-upgrade ; sudo apt clean > /dev/null 2>> ~/.error.log
  echo_info "++++++++++"
  echo_ok "Update Complete"
  echo_info "Installing ZSH"
  sudo apt install -y zsh &&
    echo_ok "Installaion OK!"
  echo_info "Done"
}

function config_bashrc(){
#cat >> ~/.bashrc <<EOL
#cat >> ~/.zshrc <<EOL

cat >> $HOME/git/repository/scripts/testfile <<EOL

#COLORS
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

#ALIAS
alias ll='ls -la'
alias '..'='cd ..'
alias bashrc='vim ~/.bashrc'
alias zshrc='vim ~/.zshrc'
alias srcbashrc='source ~/.bashrc'
alias srczshrc='source ~/.zshrc'
alias vi='vim'
alias clr='clear'
alias fu='apt update && apt full-upgrade && apt clean'
alias home='cd /home/david/'
alias res='tput sgr 0'
alias pill='echo -e "${NOCOLOR}KEINE FARBE," \ "
${RED}ROT,${GREEN}GRUEN,${BLUE}BLAU,${PURPLE}LILA,${CYAN}CYAN,${YELLOW}GELB,${WHITE}WEISS "'
alias please='sudo' 

#EXPORT
export HISTTIMEFORMAT="%h %d %H:%M:%S "
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTIGNORE="ll:ls:ps:history"
export -f echo_error
export -f echo_info
export -f echo_ok
export -f echo_warning
export -f res
EOL

echo_info "\n+++ bashrc configured +++"
source ~/.bashrc
source ~/.zshrc
echo_ok "\n+++ bashrc sourced and ready to use +++"
}

function full_update(){
  echo_info "Starting full system update"
  sudo apt update ; sudo apt full-upgrade ; sudo apt clean
  echo_ok "Full system update done"
}

function init_git_home(){
  echo_info "Init user git hime directory"
  [[ ! -d $HOME/git/repository ]] && 
   mkdir -p $HOME/git/repository &&
  echo_ok "User directory for $USER initialized"
}

function set_git_editor(){
  echo_info "Setting vim as the default git editor"
  git config --global core.editor "vim"
  echo_ok "vim is now the new default editor for git"
}

function install_btop_raspbian(){
  echo_info "Installing btop on raspbian devices"
  echo_info "Determining if system is running raspbian"
  if cat /etc/apt/sources.list.d/raspi.list | grep -q "raspberrypi"; then
    echo_ok "System using raspbian, continuing"
    echo_info "Installing btop"
    wget -qO btop.tbz https://github.com/aristocratos/btop/releases/latest/download/btop-armv7l-linux-musleabihf.tbz
  sudo tar xf btop.tbz -C /usr/local bin/btop && rm -rf btop.tbz &&
  echo_ok "btop installed"
  
  else
    echo_error "System is not using raspbian, aborting!"
  fi
}
