#!/bin/bash
#tech_functions

##
# BASH menu script that checks:
#   - Memory usage
#   - CPU load
#   - Number of TCP connections 
#   - Kernel version
##

server_name=$(hostname)

function memory_check() {
    echo ""
	echo "Memory usage on ${server_name} is: "
	free -h
	echo ""
}

function cpu_check() {
    echo ""
	echo "CPU load on ${server_name} is: "
    echo ""
	uptime
    echo ""
}

function tcp_check() {
    echo ""
	echo "TCP connections on ${server_name}: "
    echo ""
	cat  /proc/net/tcp | wc -l
    echo ""
}

function kernel_check() {
    echo ""
	echo "Kernel version on ${server_name} is: "
	echo ""
	uname -r
    echo ""
}

function all_checks() {
	memory_check
	cpu_check
	tcp_check
	kernel_check
}

function temperature_check(){
temp_crit=45
  echo_info "Checking current CPU temperature"
 # TEMP=$(vcgencmd measure_temp | sed -e 's/temp=//')
  TEMP=$(vcgencmd measure_temp | sed "s/[^0-9.]//g")
  if ["$TEMP" -ge "$temp_crit"]; then
    echo_warning "Temperature at "$TEMP"°C"
  else
    echo_error "Temperature at "$TEMP"°C"
  fi
}
